#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2025 Microsoft Corporation
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public
# License as published by the Free Software Foundation.

function usage() {
    echo "Sample script for extracting instructions and map data out of" >&2
    echo "autogenerated eBPF lskel headers" >&2
    echo "" >&2
    echo "USAGE: header_file field" >&2
    exit 1
}

ARGC=$#

EXPECTED_ARGS=2

if [ $ARGC -ne $EXPECTED_ARGS ] ; then
    usage
fi

# See extract-insn.sh for the rationale behind the sed/printf '%b' shape.
HEADER="$1"
FIELD="$2"

# Reject anything that could escape into the sed pattern below.
case "$FIELD" in
    *[!A-Za-z0-9_]*|"")
        echo "$(basename "$0"): invalid field name '$FIELD'" >&2
        exit 1
        ;;
esac

STR=$(gcc -E "$HEADER" | \
      sed -n "s/.*char opts_${FIELD}[[:space:]]*\[\][^=]*=[[:space:]]*\"\(.*\)\"[[:space:]]*;.*/\1/p")

if [ -z "$STR" ]; then
    echo "$(basename "$0"): no opts_${FIELD}[] declaration found in $HEADER" >&2
    exit 1
fi

printf '%b' "$STR"
