iris-objs += iris_core.o \
             iris_hfi_gen1_command.o \
             iris_hfi_gen2_command.o \
             iris_hfi_queue.o \
             iris_platform_sm8250.o \
             iris_platform_sm8550.o \
             iris_probe.o \
             iris_resources.o \
             iris_vidc.o \

obj-$(CONFIG_VIDEO_QCOM_IRIS) += iris.o
